// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#include "base.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace natashabasepb {
class SymbolLineDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SymbolLine>
      _instance;
} _SymbolLine_default_instance_;
class SymbolBlockDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SymbolBlock>
      _instance;
} _SymbolBlock_default_instance_;
class SymbolBlock3X5DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SymbolBlock3X5>
      _instance;
} _SymbolBlock3X5_default_instance_;
}  // namespace natashabasepb
namespace protobuf_base_2eproto {
void InitDefaultsSymbolLineImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::natashabasepb::_SymbolLine_default_instance_;
    new (ptr) ::natashabasepb::SymbolLine();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::natashabasepb::SymbolLine::InitAsDefaultInstance();
}

void InitDefaultsSymbolLine() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSymbolLineImpl);
}

void InitDefaultsSymbolBlockImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_base_2eproto::InitDefaultsSymbolLine();
  {
    void* ptr = &::natashabasepb::_SymbolBlock_default_instance_;
    new (ptr) ::natashabasepb::SymbolBlock();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::natashabasepb::SymbolBlock::InitAsDefaultInstance();
}

void InitDefaultsSymbolBlock() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSymbolBlockImpl);
}

void InitDefaultsSymbolBlock3X5Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::natashabasepb::_SymbolBlock3X5_default_instance_;
    new (ptr) ::natashabasepb::SymbolBlock3X5();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::natashabasepb::SymbolBlock3X5::InitAsDefaultInstance();
}

void InitDefaultsSymbolBlock3X5() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSymbolBlock3X5Impl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolLine, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolLine, xdat_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock, ydat_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat0_0_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat0_1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat0_2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat0_3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat0_4_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat1_0_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat1_1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat1_2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat1_3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat1_4_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat2_0_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat2_1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat2_2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat2_3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::natashabasepb::SymbolBlock3X5, dat2_4_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::natashabasepb::SymbolLine)},
  { 6, -1, sizeof(::natashabasepb::SymbolBlock)},
  { 12, -1, sizeof(::natashabasepb::SymbolBlock3X5)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::natashabasepb::_SymbolLine_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::natashabasepb::_SymbolBlock_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::natashabasepb::_SymbolBlock3X5_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "base.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\nbase.proto\022\rnatashabasepb\"\032\n\nSymbolLin"
      "e\022\014\n\004xdat\030\001 \003(\005\"6\n\013SymbolBlock\022\'\n\004ydat\030\001"
      " \003(\0132\031.natashabasepb.SymbolLine\"\200\002\n\016Symb"
      "olBlock3X5\022\016\n\006dat0_0\030\001 \001(\005\022\016\n\006dat0_1\030\002 \001"
      "(\005\022\016\n\006dat0_2\030\003 \001(\005\022\016\n\006dat0_3\030\004 \001(\005\022\016\n\006da"
      "t0_4\030\005 \001(\005\022\016\n\006dat1_0\030\006 \001(\005\022\016\n\006dat1_1\030\007 \001"
      "(\005\022\016\n\006dat1_2\030\010 \001(\005\022\016\n\006dat1_3\030\t \001(\005\022\016\n\006da"
      "t1_4\030\n \001(\005\022\016\n\006dat2_0\030\013 \001(\005\022\016\n\006dat2_1\030\014 \001"
      "(\005\022\016\n\006dat2_2\030\r \001(\005\022\016\n\006dat2_3\030\016 \001(\005\022\016\n\006da"
      "t2_4\030\017 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 378);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "base.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_base_2eproto
namespace natashabasepb {

// ===================================================================

void SymbolLine::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SymbolLine::kXdatFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SymbolLine::SymbolLine()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_base_2eproto::InitDefaultsSymbolLine();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:natashabasepb.SymbolLine)
}
SymbolLine::SymbolLine(const SymbolLine& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      xdat_(from.xdat_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:natashabasepb.SymbolLine)
}

void SymbolLine::SharedCtor() {
  _cached_size_ = 0;
}

SymbolLine::~SymbolLine() {
  // @@protoc_insertion_point(destructor:natashabasepb.SymbolLine)
  SharedDtor();
}

void SymbolLine::SharedDtor() {
}

void SymbolLine::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SymbolLine::descriptor() {
  ::protobuf_base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_base_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SymbolLine& SymbolLine::default_instance() {
  ::protobuf_base_2eproto::InitDefaultsSymbolLine();
  return *internal_default_instance();
}


void SymbolLine::Clear() {
// @@protoc_insertion_point(message_clear_start:natashabasepb.SymbolLine)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  xdat_.Clear();
  _internal_metadata_.Clear();
}

bool SymbolLine::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:natashabasepb.SymbolLine)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 xdat = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_xdat())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10u, input, this->mutable_xdat())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:natashabasepb.SymbolLine)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:natashabasepb.SymbolLine)
  return false;
#undef DO_
}

void SymbolLine::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:natashabasepb.SymbolLine)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 xdat = 1;
  if (this->xdat_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _xdat_cached_byte_size_));
  }
  for (int i = 0, n = this->xdat_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->xdat(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:natashabasepb.SymbolLine)
}

::google::protobuf::uint8* SymbolLine::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:natashabasepb.SymbolLine)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 xdat = 1;
  if (this->xdat_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _xdat_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->xdat_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:natashabasepb.SymbolLine)
  return target;
}

size_t SymbolLine::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:natashabasepb.SymbolLine)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 xdat = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->xdat_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _xdat_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SymbolLine::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:natashabasepb.SymbolLine)
  GOOGLE_DCHECK_NE(&from, this);
  const SymbolLine* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SymbolLine>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:natashabasepb.SymbolLine)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:natashabasepb.SymbolLine)
    MergeFrom(*source);
  }
}

void SymbolLine::MergeFrom(const SymbolLine& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:natashabasepb.SymbolLine)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  xdat_.MergeFrom(from.xdat_);
}

void SymbolLine::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:natashabasepb.SymbolLine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SymbolLine::CopyFrom(const SymbolLine& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:natashabasepb.SymbolLine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SymbolLine::IsInitialized() const {
  return true;
}

void SymbolLine::Swap(SymbolLine* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SymbolLine::InternalSwap(SymbolLine* other) {
  using std::swap;
  xdat_.InternalSwap(&other->xdat_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SymbolLine::GetMetadata() const {
  protobuf_base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_base_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SymbolBlock::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SymbolBlock::kYdatFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SymbolBlock::SymbolBlock()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_base_2eproto::InitDefaultsSymbolBlock();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:natashabasepb.SymbolBlock)
}
SymbolBlock::SymbolBlock(const SymbolBlock& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      ydat_(from.ydat_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:natashabasepb.SymbolBlock)
}

void SymbolBlock::SharedCtor() {
  _cached_size_ = 0;
}

SymbolBlock::~SymbolBlock() {
  // @@protoc_insertion_point(destructor:natashabasepb.SymbolBlock)
  SharedDtor();
}

void SymbolBlock::SharedDtor() {
}

void SymbolBlock::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SymbolBlock::descriptor() {
  ::protobuf_base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_base_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SymbolBlock& SymbolBlock::default_instance() {
  ::protobuf_base_2eproto::InitDefaultsSymbolBlock();
  return *internal_default_instance();
}


void SymbolBlock::Clear() {
// @@protoc_insertion_point(message_clear_start:natashabasepb.SymbolBlock)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ydat_.Clear();
  _internal_metadata_.Clear();
}

bool SymbolBlock::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:natashabasepb.SymbolBlock)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .natashabasepb.SymbolLine ydat = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_ydat()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:natashabasepb.SymbolBlock)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:natashabasepb.SymbolBlock)
  return false;
#undef DO_
}

void SymbolBlock::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:natashabasepb.SymbolBlock)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .natashabasepb.SymbolLine ydat = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->ydat_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->ydat(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:natashabasepb.SymbolBlock)
}

::google::protobuf::uint8* SymbolBlock::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:natashabasepb.SymbolBlock)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .natashabasepb.SymbolLine ydat = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->ydat_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->ydat(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:natashabasepb.SymbolBlock)
  return target;
}

size_t SymbolBlock::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:natashabasepb.SymbolBlock)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .natashabasepb.SymbolLine ydat = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->ydat_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->ydat(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SymbolBlock::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:natashabasepb.SymbolBlock)
  GOOGLE_DCHECK_NE(&from, this);
  const SymbolBlock* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SymbolBlock>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:natashabasepb.SymbolBlock)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:natashabasepb.SymbolBlock)
    MergeFrom(*source);
  }
}

void SymbolBlock::MergeFrom(const SymbolBlock& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:natashabasepb.SymbolBlock)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  ydat_.MergeFrom(from.ydat_);
}

void SymbolBlock::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:natashabasepb.SymbolBlock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SymbolBlock::CopyFrom(const SymbolBlock& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:natashabasepb.SymbolBlock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SymbolBlock::IsInitialized() const {
  return true;
}

void SymbolBlock::Swap(SymbolBlock* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SymbolBlock::InternalSwap(SymbolBlock* other) {
  using std::swap;
  CastToBase(&ydat_)->InternalSwap(CastToBase(&other->ydat_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SymbolBlock::GetMetadata() const {
  protobuf_base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_base_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SymbolBlock3X5::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SymbolBlock3X5::kDat00FieldNumber;
const int SymbolBlock3X5::kDat01FieldNumber;
const int SymbolBlock3X5::kDat02FieldNumber;
const int SymbolBlock3X5::kDat03FieldNumber;
const int SymbolBlock3X5::kDat04FieldNumber;
const int SymbolBlock3X5::kDat10FieldNumber;
const int SymbolBlock3X5::kDat11FieldNumber;
const int SymbolBlock3X5::kDat12FieldNumber;
const int SymbolBlock3X5::kDat13FieldNumber;
const int SymbolBlock3X5::kDat14FieldNumber;
const int SymbolBlock3X5::kDat20FieldNumber;
const int SymbolBlock3X5::kDat21FieldNumber;
const int SymbolBlock3X5::kDat22FieldNumber;
const int SymbolBlock3X5::kDat23FieldNumber;
const int SymbolBlock3X5::kDat24FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SymbolBlock3X5::SymbolBlock3X5()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_base_2eproto::InitDefaultsSymbolBlock3X5();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:natashabasepb.SymbolBlock3X5)
}
SymbolBlock3X5::SymbolBlock3X5(const SymbolBlock3X5& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&dat0_0_, &from.dat0_0_,
    static_cast<size_t>(reinterpret_cast<char*>(&dat2_4_) -
    reinterpret_cast<char*>(&dat0_0_)) + sizeof(dat2_4_));
  // @@protoc_insertion_point(copy_constructor:natashabasepb.SymbolBlock3X5)
}

void SymbolBlock3X5::SharedCtor() {
  ::memset(&dat0_0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dat2_4_) -
      reinterpret_cast<char*>(&dat0_0_)) + sizeof(dat2_4_));
  _cached_size_ = 0;
}

SymbolBlock3X5::~SymbolBlock3X5() {
  // @@protoc_insertion_point(destructor:natashabasepb.SymbolBlock3X5)
  SharedDtor();
}

void SymbolBlock3X5::SharedDtor() {
}

void SymbolBlock3X5::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SymbolBlock3X5::descriptor() {
  ::protobuf_base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_base_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SymbolBlock3X5& SymbolBlock3X5::default_instance() {
  ::protobuf_base_2eproto::InitDefaultsSymbolBlock3X5();
  return *internal_default_instance();
}


void SymbolBlock3X5::Clear() {
// @@protoc_insertion_point(message_clear_start:natashabasepb.SymbolBlock3X5)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&dat0_0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dat2_4_) -
      reinterpret_cast<char*>(&dat0_0_)) + sizeof(dat2_4_));
  _internal_metadata_.Clear();
}

bool SymbolBlock3X5::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:natashabasepb.SymbolBlock3X5)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 dat0_0 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat0_0_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat0_1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat0_1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat0_2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat0_2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat0_3 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat0_3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat0_4 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat0_4_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat1_0 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat1_0_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat1_1 = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat1_1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat1_2 = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat1_2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat1_3 = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat1_3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat1_4 = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat1_4_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat2_0 = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat2_0_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat2_1 = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat2_1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat2_2 = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(104u /* 104 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat2_2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat2_3 = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u /* 112 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat2_3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dat2_4 = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(120u /* 120 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dat2_4_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:natashabasepb.SymbolBlock3X5)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:natashabasepb.SymbolBlock3X5)
  return false;
#undef DO_
}

void SymbolBlock3X5::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:natashabasepb.SymbolBlock3X5)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 dat0_0 = 1;
  if (this->dat0_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->dat0_0(), output);
  }

  // int32 dat0_1 = 2;
  if (this->dat0_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->dat0_1(), output);
  }

  // int32 dat0_2 = 3;
  if (this->dat0_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->dat0_2(), output);
  }

  // int32 dat0_3 = 4;
  if (this->dat0_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->dat0_3(), output);
  }

  // int32 dat0_4 = 5;
  if (this->dat0_4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->dat0_4(), output);
  }

  // int32 dat1_0 = 6;
  if (this->dat1_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->dat1_0(), output);
  }

  // int32 dat1_1 = 7;
  if (this->dat1_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->dat1_1(), output);
  }

  // int32 dat1_2 = 8;
  if (this->dat1_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->dat1_2(), output);
  }

  // int32 dat1_3 = 9;
  if (this->dat1_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->dat1_3(), output);
  }

  // int32 dat1_4 = 10;
  if (this->dat1_4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->dat1_4(), output);
  }

  // int32 dat2_0 = 11;
  if (this->dat2_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->dat2_0(), output);
  }

  // int32 dat2_1 = 12;
  if (this->dat2_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->dat2_1(), output);
  }

  // int32 dat2_2 = 13;
  if (this->dat2_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->dat2_2(), output);
  }

  // int32 dat2_3 = 14;
  if (this->dat2_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(14, this->dat2_3(), output);
  }

  // int32 dat2_4 = 15;
  if (this->dat2_4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(15, this->dat2_4(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:natashabasepb.SymbolBlock3X5)
}

::google::protobuf::uint8* SymbolBlock3X5::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:natashabasepb.SymbolBlock3X5)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 dat0_0 = 1;
  if (this->dat0_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->dat0_0(), target);
  }

  // int32 dat0_1 = 2;
  if (this->dat0_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->dat0_1(), target);
  }

  // int32 dat0_2 = 3;
  if (this->dat0_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->dat0_2(), target);
  }

  // int32 dat0_3 = 4;
  if (this->dat0_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->dat0_3(), target);
  }

  // int32 dat0_4 = 5;
  if (this->dat0_4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->dat0_4(), target);
  }

  // int32 dat1_0 = 6;
  if (this->dat1_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->dat1_0(), target);
  }

  // int32 dat1_1 = 7;
  if (this->dat1_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->dat1_1(), target);
  }

  // int32 dat1_2 = 8;
  if (this->dat1_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->dat1_2(), target);
  }

  // int32 dat1_3 = 9;
  if (this->dat1_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->dat1_3(), target);
  }

  // int32 dat1_4 = 10;
  if (this->dat1_4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->dat1_4(), target);
  }

  // int32 dat2_0 = 11;
  if (this->dat2_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->dat2_0(), target);
  }

  // int32 dat2_1 = 12;
  if (this->dat2_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->dat2_1(), target);
  }

  // int32 dat2_2 = 13;
  if (this->dat2_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->dat2_2(), target);
  }

  // int32 dat2_3 = 14;
  if (this->dat2_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(14, this->dat2_3(), target);
  }

  // int32 dat2_4 = 15;
  if (this->dat2_4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(15, this->dat2_4(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:natashabasepb.SymbolBlock3X5)
  return target;
}

size_t SymbolBlock3X5::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:natashabasepb.SymbolBlock3X5)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 dat0_0 = 1;
  if (this->dat0_0() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat0_0());
  }

  // int32 dat0_1 = 2;
  if (this->dat0_1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat0_1());
  }

  // int32 dat0_2 = 3;
  if (this->dat0_2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat0_2());
  }

  // int32 dat0_3 = 4;
  if (this->dat0_3() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat0_3());
  }

  // int32 dat0_4 = 5;
  if (this->dat0_4() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat0_4());
  }

  // int32 dat1_0 = 6;
  if (this->dat1_0() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat1_0());
  }

  // int32 dat1_1 = 7;
  if (this->dat1_1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat1_1());
  }

  // int32 dat1_2 = 8;
  if (this->dat1_2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat1_2());
  }

  // int32 dat1_3 = 9;
  if (this->dat1_3() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat1_3());
  }

  // int32 dat1_4 = 10;
  if (this->dat1_4() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat1_4());
  }

  // int32 dat2_0 = 11;
  if (this->dat2_0() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat2_0());
  }

  // int32 dat2_1 = 12;
  if (this->dat2_1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat2_1());
  }

  // int32 dat2_2 = 13;
  if (this->dat2_2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat2_2());
  }

  // int32 dat2_3 = 14;
  if (this->dat2_3() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat2_3());
  }

  // int32 dat2_4 = 15;
  if (this->dat2_4() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dat2_4());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SymbolBlock3X5::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:natashabasepb.SymbolBlock3X5)
  GOOGLE_DCHECK_NE(&from, this);
  const SymbolBlock3X5* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SymbolBlock3X5>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:natashabasepb.SymbolBlock3X5)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:natashabasepb.SymbolBlock3X5)
    MergeFrom(*source);
  }
}

void SymbolBlock3X5::MergeFrom(const SymbolBlock3X5& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:natashabasepb.SymbolBlock3X5)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.dat0_0() != 0) {
    set_dat0_0(from.dat0_0());
  }
  if (from.dat0_1() != 0) {
    set_dat0_1(from.dat0_1());
  }
  if (from.dat0_2() != 0) {
    set_dat0_2(from.dat0_2());
  }
  if (from.dat0_3() != 0) {
    set_dat0_3(from.dat0_3());
  }
  if (from.dat0_4() != 0) {
    set_dat0_4(from.dat0_4());
  }
  if (from.dat1_0() != 0) {
    set_dat1_0(from.dat1_0());
  }
  if (from.dat1_1() != 0) {
    set_dat1_1(from.dat1_1());
  }
  if (from.dat1_2() != 0) {
    set_dat1_2(from.dat1_2());
  }
  if (from.dat1_3() != 0) {
    set_dat1_3(from.dat1_3());
  }
  if (from.dat1_4() != 0) {
    set_dat1_4(from.dat1_4());
  }
  if (from.dat2_0() != 0) {
    set_dat2_0(from.dat2_0());
  }
  if (from.dat2_1() != 0) {
    set_dat2_1(from.dat2_1());
  }
  if (from.dat2_2() != 0) {
    set_dat2_2(from.dat2_2());
  }
  if (from.dat2_3() != 0) {
    set_dat2_3(from.dat2_3());
  }
  if (from.dat2_4() != 0) {
    set_dat2_4(from.dat2_4());
  }
}

void SymbolBlock3X5::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:natashabasepb.SymbolBlock3X5)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SymbolBlock3X5::CopyFrom(const SymbolBlock3X5& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:natashabasepb.SymbolBlock3X5)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SymbolBlock3X5::IsInitialized() const {
  return true;
}

void SymbolBlock3X5::Swap(SymbolBlock3X5* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SymbolBlock3X5::InternalSwap(SymbolBlock3X5* other) {
  using std::swap;
  swap(dat0_0_, other->dat0_0_);
  swap(dat0_1_, other->dat0_1_);
  swap(dat0_2_, other->dat0_2_);
  swap(dat0_3_, other->dat0_3_);
  swap(dat0_4_, other->dat0_4_);
  swap(dat1_0_, other->dat1_0_);
  swap(dat1_1_, other->dat1_1_);
  swap(dat1_2_, other->dat1_2_);
  swap(dat1_3_, other->dat1_3_);
  swap(dat1_4_, other->dat1_4_);
  swap(dat2_0_, other->dat2_0_);
  swap(dat2_1_, other->dat2_1_);
  swap(dat2_2_, other->dat2_2_);
  swap(dat2_3_, other->dat2_3_);
  swap(dat2_4_, other->dat2_4_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SymbolBlock3X5::GetMetadata() const {
  protobuf_base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_base_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace natashabasepb
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::natashabasepb::SymbolLine* Arena::Create< ::natashabasepb::SymbolLine >(Arena* arena) {
  return Arena::CreateInternal< ::natashabasepb::SymbolLine >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::natashabasepb::SymbolBlock* Arena::Create< ::natashabasepb::SymbolBlock >(Arena* arena) {
  return Arena::CreateInternal< ::natashabasepb::SymbolBlock >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::natashabasepb::SymbolBlock3X5* Arena::Create< ::natashabasepb::SymbolBlock3X5 >(Arena* arena) {
  return Arena::CreateInternal< ::natashabasepb::SymbolBlock3X5 >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
