// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef PROTOBUF_base_2eproto__INCLUDED
#define PROTOBUF_base_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)

namespace protobuf_base_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSymbolLineImpl();
void InitDefaultsSymbolLine();
void InitDefaultsSymbolBlockImpl();
void InitDefaultsSymbolBlock();
void InitDefaultsSymbolBlock3X5Impl();
void InitDefaultsSymbolBlock3X5();
void InitDefaultsRandomResultImpl();
void InitDefaultsRandomResult();
void InitDefaultsStaticCascadingRandomResultImpl();
void InitDefaultsStaticCascadingRandomResult();
void InitDefaultsPosition2DImpl();
void InitDefaultsPosition2D();
void InitDefaultsGameResultInfoImpl();
void InitDefaultsGameResultInfo();
void InitDefaultsGameResultChunkImpl();
void InitDefaultsGameResultChunk();
inline void InitDefaults() {
  InitDefaultsSymbolLine();
  InitDefaultsSymbolBlock();
  InitDefaultsSymbolBlock3X5();
  InitDefaultsRandomResult();
  InitDefaultsStaticCascadingRandomResult();
  InitDefaultsPosition2D();
  InitDefaultsGameResultInfo();
  InitDefaultsGameResultChunk();
}
}  // namespace protobuf_base_2eproto
namespace natashapb {
class GameResultChunk;
class GameResultChunkDefaultTypeInternal;
extern GameResultChunkDefaultTypeInternal _GameResultChunk_default_instance_;
class GameResultInfo;
class GameResultInfoDefaultTypeInternal;
extern GameResultInfoDefaultTypeInternal _GameResultInfo_default_instance_;
class Position2D;
class Position2DDefaultTypeInternal;
extern Position2DDefaultTypeInternal _Position2D_default_instance_;
class RandomResult;
class RandomResultDefaultTypeInternal;
extern RandomResultDefaultTypeInternal _RandomResult_default_instance_;
class StaticCascadingRandomResult;
class StaticCascadingRandomResultDefaultTypeInternal;
extern StaticCascadingRandomResultDefaultTypeInternal _StaticCascadingRandomResult_default_instance_;
class SymbolBlock;
class SymbolBlockDefaultTypeInternal;
extern SymbolBlockDefaultTypeInternal _SymbolBlock_default_instance_;
class SymbolBlock3X5;
class SymbolBlock3X5DefaultTypeInternal;
extern SymbolBlock3X5DefaultTypeInternal _SymbolBlock3X5_default_instance_;
class SymbolLine;
class SymbolLineDefaultTypeInternal;
extern SymbolLineDefaultTypeInternal _SymbolLine_default_instance_;
}  // namespace natashapb
namespace google {
namespace protobuf {
template<> ::natashapb::GameResultChunk* Arena::Create< ::natashapb::GameResultChunk>(Arena*);
template<> ::natashapb::GameResultInfo* Arena::Create< ::natashapb::GameResultInfo>(Arena*);
template<> ::natashapb::Position2D* Arena::Create< ::natashapb::Position2D>(Arena*);
template<> ::natashapb::RandomResult* Arena::Create< ::natashapb::RandomResult>(Arena*);
template<> ::natashapb::StaticCascadingRandomResult* Arena::Create< ::natashapb::StaticCascadingRandomResult>(Arena*);
template<> ::natashapb::SymbolBlock* Arena::Create< ::natashapb::SymbolBlock>(Arena*);
template<> ::natashapb::SymbolBlock3X5* Arena::Create< ::natashapb::SymbolBlock3X5>(Arena*);
template<> ::natashapb::SymbolLine* Arena::Create< ::natashapb::SymbolLine>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace natashapb {

enum GAMERESULTTYPE {
  NULL_ = 0,
  LINE_LEFT = 1,
  LINE_RIGHT = 2,
  SCATTER_LEFT = 3,
  SCATTER_RIGHT = 4,
  SCATTER_LEFT_CONSEQUENT = 5,
  SCATTER_RIGHT_CONSEQUENT = 6,
  GAMERESULTTYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GAMERESULTTYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GAMERESULTTYPE_IsValid(int value);
const GAMERESULTTYPE GAMERESULTTYPE_MIN = NULL_;
const GAMERESULTTYPE GAMERESULTTYPE_MAX = SCATTER_RIGHT_CONSEQUENT;
const int GAMERESULTTYPE_ARRAYSIZE = GAMERESULTTYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* GAMERESULTTYPE_descriptor();
inline const ::std::string& GAMERESULTTYPE_Name(GAMERESULTTYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    GAMERESULTTYPE_descriptor(), value);
}
inline bool GAMERESULTTYPE_Parse(
    const ::std::string& name, GAMERESULTTYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GAMERESULTTYPE>(
    GAMERESULTTYPE_descriptor(), name, value);
}
// ===================================================================

class SymbolLine : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.SymbolLine) */ {
 public:
  SymbolLine();
  virtual ~SymbolLine();

  SymbolLine(const SymbolLine& from);

  inline SymbolLine& operator=(const SymbolLine& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SymbolLine(SymbolLine&& from) noexcept
    : SymbolLine() {
    *this = ::std::move(from);
  }

  inline SymbolLine& operator=(SymbolLine&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SymbolLine& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SymbolLine* internal_default_instance() {
    return reinterpret_cast<const SymbolLine*>(
               &_SymbolLine_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SymbolLine* other);
  friend void swap(SymbolLine& a, SymbolLine& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SymbolLine* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<SymbolLine>(NULL);
  }

  SymbolLine* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<SymbolLine>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SymbolLine& from);
  void MergeFrom(const SymbolLine& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SymbolLine* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 xDat = 1;
  int xdat_size() const;
  void clear_xdat();
  static const int kXDatFieldNumber = 1;
  ::google::protobuf::int32 xdat(int index) const;
  void set_xdat(int index, ::google::protobuf::int32 value);
  void add_xdat(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      xdat() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_xdat();

  // @@protoc_insertion_point(class_scope:natashapb.SymbolLine)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > xdat_;
  mutable int _xdat_cached_byte_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsSymbolLineImpl();
};
// -------------------------------------------------------------------

class SymbolBlock : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.SymbolBlock) */ {
 public:
  SymbolBlock();
  virtual ~SymbolBlock();

  SymbolBlock(const SymbolBlock& from);

  inline SymbolBlock& operator=(const SymbolBlock& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SymbolBlock(SymbolBlock&& from) noexcept
    : SymbolBlock() {
    *this = ::std::move(from);
  }

  inline SymbolBlock& operator=(SymbolBlock&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SymbolBlock& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SymbolBlock* internal_default_instance() {
    return reinterpret_cast<const SymbolBlock*>(
               &_SymbolBlock_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SymbolBlock* other);
  friend void swap(SymbolBlock& a, SymbolBlock& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SymbolBlock* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<SymbolBlock>(NULL);
  }

  SymbolBlock* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<SymbolBlock>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SymbolBlock& from);
  void MergeFrom(const SymbolBlock& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SymbolBlock* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .natashapb.SymbolLine yDat = 1;
  int ydat_size() const;
  void clear_ydat();
  static const int kYDatFieldNumber = 1;
  ::natashapb::SymbolLine* mutable_ydat(int index);
  ::google::protobuf::RepeatedPtrField< ::natashapb::SymbolLine >*
      mutable_ydat();
  const ::natashapb::SymbolLine& ydat(int index) const;
  ::natashapb::SymbolLine* add_ydat();
  const ::google::protobuf::RepeatedPtrField< ::natashapb::SymbolLine >&
      ydat() const;

  // @@protoc_insertion_point(class_scope:natashapb.SymbolBlock)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::natashapb::SymbolLine > ydat_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsSymbolBlockImpl();
};
// -------------------------------------------------------------------

class SymbolBlock3X5 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.SymbolBlock3X5) */ {
 public:
  SymbolBlock3X5();
  virtual ~SymbolBlock3X5();

  SymbolBlock3X5(const SymbolBlock3X5& from);

  inline SymbolBlock3X5& operator=(const SymbolBlock3X5& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SymbolBlock3X5(SymbolBlock3X5&& from) noexcept
    : SymbolBlock3X5() {
    *this = ::std::move(from);
  }

  inline SymbolBlock3X5& operator=(SymbolBlock3X5&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SymbolBlock3X5& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SymbolBlock3X5* internal_default_instance() {
    return reinterpret_cast<const SymbolBlock3X5*>(
               &_SymbolBlock3X5_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(SymbolBlock3X5* other);
  friend void swap(SymbolBlock3X5& a, SymbolBlock3X5& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SymbolBlock3X5* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<SymbolBlock3X5>(NULL);
  }

  SymbolBlock3X5* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<SymbolBlock3X5>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SymbolBlock3X5& from);
  void MergeFrom(const SymbolBlock3X5& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SymbolBlock3X5* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 dat0_0 = 1;
  void clear_dat0_0();
  static const int kDat00FieldNumber = 1;
  ::google::protobuf::int32 dat0_0() const;
  void set_dat0_0(::google::protobuf::int32 value);

  // int32 dat0_1 = 2;
  void clear_dat0_1();
  static const int kDat01FieldNumber = 2;
  ::google::protobuf::int32 dat0_1() const;
  void set_dat0_1(::google::protobuf::int32 value);

  // int32 dat0_2 = 3;
  void clear_dat0_2();
  static const int kDat02FieldNumber = 3;
  ::google::protobuf::int32 dat0_2() const;
  void set_dat0_2(::google::protobuf::int32 value);

  // int32 dat0_3 = 4;
  void clear_dat0_3();
  static const int kDat03FieldNumber = 4;
  ::google::protobuf::int32 dat0_3() const;
  void set_dat0_3(::google::protobuf::int32 value);

  // int32 dat0_4 = 5;
  void clear_dat0_4();
  static const int kDat04FieldNumber = 5;
  ::google::protobuf::int32 dat0_4() const;
  void set_dat0_4(::google::protobuf::int32 value);

  // int32 dat1_0 = 6;
  void clear_dat1_0();
  static const int kDat10FieldNumber = 6;
  ::google::protobuf::int32 dat1_0() const;
  void set_dat1_0(::google::protobuf::int32 value);

  // int32 dat1_1 = 7;
  void clear_dat1_1();
  static const int kDat11FieldNumber = 7;
  ::google::protobuf::int32 dat1_1() const;
  void set_dat1_1(::google::protobuf::int32 value);

  // int32 dat1_2 = 8;
  void clear_dat1_2();
  static const int kDat12FieldNumber = 8;
  ::google::protobuf::int32 dat1_2() const;
  void set_dat1_2(::google::protobuf::int32 value);

  // int32 dat1_3 = 9;
  void clear_dat1_3();
  static const int kDat13FieldNumber = 9;
  ::google::protobuf::int32 dat1_3() const;
  void set_dat1_3(::google::protobuf::int32 value);

  // int32 dat1_4 = 10;
  void clear_dat1_4();
  static const int kDat14FieldNumber = 10;
  ::google::protobuf::int32 dat1_4() const;
  void set_dat1_4(::google::protobuf::int32 value);

  // int32 dat2_0 = 11;
  void clear_dat2_0();
  static const int kDat20FieldNumber = 11;
  ::google::protobuf::int32 dat2_0() const;
  void set_dat2_0(::google::protobuf::int32 value);

  // int32 dat2_1 = 12;
  void clear_dat2_1();
  static const int kDat21FieldNumber = 12;
  ::google::protobuf::int32 dat2_1() const;
  void set_dat2_1(::google::protobuf::int32 value);

  // int32 dat2_2 = 13;
  void clear_dat2_2();
  static const int kDat22FieldNumber = 13;
  ::google::protobuf::int32 dat2_2() const;
  void set_dat2_2(::google::protobuf::int32 value);

  // int32 dat2_3 = 14;
  void clear_dat2_3();
  static const int kDat23FieldNumber = 14;
  ::google::protobuf::int32 dat2_3() const;
  void set_dat2_3(::google::protobuf::int32 value);

  // int32 dat2_4 = 15;
  void clear_dat2_4();
  static const int kDat24FieldNumber = 15;
  ::google::protobuf::int32 dat2_4() const;
  void set_dat2_4(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:natashapb.SymbolBlock3X5)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 dat0_0_;
  ::google::protobuf::int32 dat0_1_;
  ::google::protobuf::int32 dat0_2_;
  ::google::protobuf::int32 dat0_3_;
  ::google::protobuf::int32 dat0_4_;
  ::google::protobuf::int32 dat1_0_;
  ::google::protobuf::int32 dat1_1_;
  ::google::protobuf::int32 dat1_2_;
  ::google::protobuf::int32 dat1_3_;
  ::google::protobuf::int32 dat1_4_;
  ::google::protobuf::int32 dat2_0_;
  ::google::protobuf::int32 dat2_1_;
  ::google::protobuf::int32 dat2_2_;
  ::google::protobuf::int32 dat2_3_;
  ::google::protobuf::int32 dat2_4_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsSymbolBlock3X5Impl();
};
// -------------------------------------------------------------------

class RandomResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.RandomResult) */ {
 public:
  RandomResult();
  virtual ~RandomResult();

  RandomResult(const RandomResult& from);

  inline RandomResult& operator=(const RandomResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RandomResult(RandomResult&& from) noexcept
    : RandomResult() {
    *this = ::std::move(from);
  }

  inline RandomResult& operator=(RandomResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RandomResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RandomResult* internal_default_instance() {
    return reinterpret_cast<const RandomResult*>(
               &_RandomResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(RandomResult* other);
  friend void swap(RandomResult& a, RandomResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RandomResult* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RandomResult>(NULL);
  }

  RandomResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RandomResult>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RandomResult& from);
  void MergeFrom(const RandomResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RandomResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.Any info = 1;
  bool has_info() const;
  void clear_info();
  static const int kInfoFieldNumber = 1;
  const ::google::protobuf::Any& info() const;
  ::google::protobuf::Any* release_info();
  ::google::protobuf::Any* mutable_info();
  void set_allocated_info(::google::protobuf::Any* info);

  // @@protoc_insertion_point(class_scope:natashapb.RandomResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::Any* info_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsRandomResultImpl();
};
// -------------------------------------------------------------------

class StaticCascadingRandomResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.StaticCascadingRandomResult) */ {
 public:
  StaticCascadingRandomResult();
  virtual ~StaticCascadingRandomResult();

  StaticCascadingRandomResult(const StaticCascadingRandomResult& from);

  inline StaticCascadingRandomResult& operator=(const StaticCascadingRandomResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StaticCascadingRandomResult(StaticCascadingRandomResult&& from) noexcept
    : StaticCascadingRandomResult() {
    *this = ::std::move(from);
  }

  inline StaticCascadingRandomResult& operator=(StaticCascadingRandomResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StaticCascadingRandomResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StaticCascadingRandomResult* internal_default_instance() {
    return reinterpret_cast<const StaticCascadingRandomResult*>(
               &_StaticCascadingRandomResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(StaticCascadingRandomResult* other);
  friend void swap(StaticCascadingRandomResult& a, StaticCascadingRandomResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StaticCascadingRandomResult* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<StaticCascadingRandomResult>(NULL);
  }

  StaticCascadingRandomResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<StaticCascadingRandomResult>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StaticCascadingRandomResult& from);
  void MergeFrom(const StaticCascadingRandomResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StaticCascadingRandomResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 reelsIndex = 1;
  void clear_reelsindex();
  static const int kReelsIndexFieldNumber = 1;
  ::google::protobuf::int32 reelsindex() const;
  void set_reelsindex(::google::protobuf::int32 value);

  // int32 downNums = 2;
  void clear_downnums();
  static const int kDownNumsFieldNumber = 2;
  ::google::protobuf::int32 downnums() const;
  void set_downnums(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:natashapb.StaticCascadingRandomResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 reelsindex_;
  ::google::protobuf::int32 downnums_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsStaticCascadingRandomResultImpl();
};
// -------------------------------------------------------------------

class Position2D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.Position2D) */ {
 public:
  Position2D();
  virtual ~Position2D();

  Position2D(const Position2D& from);

  inline Position2D& operator=(const Position2D& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Position2D(Position2D&& from) noexcept
    : Position2D() {
    *this = ::std::move(from);
  }

  inline Position2D& operator=(Position2D&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Position2D& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Position2D* internal_default_instance() {
    return reinterpret_cast<const Position2D*>(
               &_Position2D_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Position2D* other);
  friend void swap(Position2D& a, Position2D& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Position2D* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Position2D>(NULL);
  }

  Position2D* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Position2D>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Position2D& from);
  void MergeFrom(const Position2D& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Position2D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // int32 y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:natashapb.Position2D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsPosition2DImpl();
};
// -------------------------------------------------------------------

class GameResultInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.GameResultInfo) */ {
 public:
  GameResultInfo();
  virtual ~GameResultInfo();

  GameResultInfo(const GameResultInfo& from);

  inline GameResultInfo& operator=(const GameResultInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameResultInfo(GameResultInfo&& from) noexcept
    : GameResultInfo() {
    *this = ::std::move(from);
  }

  inline GameResultInfo& operator=(GameResultInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameResultInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameResultInfo* internal_default_instance() {
    return reinterpret_cast<const GameResultInfo*>(
               &_GameResultInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(GameResultInfo* other);
  friend void swap(GameResultInfo& a, GameResultInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameResultInfo* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GameResultInfo>(NULL);
  }

  GameResultInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GameResultInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GameResultInfo& from);
  void MergeFrom(const GameResultInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GameResultInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .natashapb.Position2D lstPos = 2;
  int lstpos_size() const;
  void clear_lstpos();
  static const int kLstPosFieldNumber = 2;
  ::natashapb::Position2D* mutable_lstpos(int index);
  ::google::protobuf::RepeatedPtrField< ::natashapb::Position2D >*
      mutable_lstpos();
  const ::natashapb::Position2D& lstpos(int index) const;
  ::natashapb::Position2D* add_lstpos();
  const ::google::protobuf::RepeatedPtrField< ::natashapb::Position2D >&
      lstpos() const;

  // repeated int32 lstSymbol = 4;
  int lstsymbol_size() const;
  void clear_lstsymbol();
  static const int kLstSymbolFieldNumber = 4;
  ::google::protobuf::int32 lstsymbol(int index) const;
  void set_lstsymbol(int index, ::google::protobuf::int32 value);
  void add_lstsymbol(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      lstsymbol() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_lstsymbol();

  // .google.protobuf.Any exDat = 7;
  bool has_exdat() const;
  void clear_exdat();
  static const int kExDatFieldNumber = 7;
  const ::google::protobuf::Any& exdat() const;
  ::google::protobuf::Any* release_exdat();
  ::google::protobuf::Any* mutable_exdat();
  void set_allocated_exdat(::google::protobuf::Any* exdat);

  // .natashapb.GAMERESULTTYPE typeGameResult = 1;
  void clear_typegameresult();
  static const int kTypeGameResultFieldNumber = 1;
  ::natashapb::GAMERESULTTYPE typegameresult() const;
  void set_typegameresult(::natashapb::GAMERESULTTYPE value);

  // int32 symbol = 3;
  void clear_symbol();
  static const int kSymbolFieldNumber = 3;
  ::google::protobuf::int32 symbol() const;
  void set_symbol(::google::protobuf::int32 value);

  // int64 win = 5;
  void clear_win();
  static const int kWinFieldNumber = 5;
  ::google::protobuf::int64 win() const;
  void set_win(::google::protobuf::int64 value);

  // int64 realWin = 6;
  void clear_realwin();
  static const int kRealWinFieldNumber = 6;
  ::google::protobuf::int64 realwin() const;
  void set_realwin(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:natashapb.GameResultInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::natashapb::Position2D > lstpos_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > lstsymbol_;
  mutable int _lstsymbol_cached_byte_size_;
  ::google::protobuf::Any* exdat_;
  int typegameresult_;
  ::google::protobuf::int32 symbol_;
  ::google::protobuf::int64 win_;
  ::google::protobuf::int64 realwin_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsGameResultInfoImpl();
};
// -------------------------------------------------------------------

class GameResultChunk : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:natashapb.GameResultChunk) */ {
 public:
  GameResultChunk();
  virtual ~GameResultChunk();

  GameResultChunk(const GameResultChunk& from);

  inline GameResultChunk& operator=(const GameResultChunk& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameResultChunk(GameResultChunk&& from) noexcept
    : GameResultChunk() {
    *this = ::std::move(from);
  }

  inline GameResultChunk& operator=(GameResultChunk&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameResultChunk& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameResultChunk* internal_default_instance() {
    return reinterpret_cast<const GameResultChunk*>(
               &_GameResultChunk_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(GameResultChunk* other);
  friend void swap(GameResultChunk& a, GameResultChunk& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameResultChunk* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GameResultChunk>(NULL);
  }

  GameResultChunk* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GameResultChunk>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GameResultChunk& from);
  void MergeFrom(const GameResultChunk& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GameResultChunk* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .natashapb.GameResultInfo lstGRI = 3;
  int lstgri_size() const;
  void clear_lstgri();
  static const int kLstGRIFieldNumber = 3;
  ::natashapb::GameResultInfo* mutable_lstgri(int index);
  ::google::protobuf::RepeatedPtrField< ::natashapb::GameResultInfo >*
      mutable_lstgri();
  const ::natashapb::GameResultInfo& lstgri(int index) const;
  ::natashapb::GameResultInfo* add_lstgri();
  const ::google::protobuf::RepeatedPtrField< ::natashapb::GameResultInfo >&
      lstgri() const;

  // .google.protobuf.Any exDat = 4;
  bool has_exdat() const;
  void clear_exdat();
  static const int kExDatFieldNumber = 4;
  const ::google::protobuf::Any& exdat() const;
  ::google::protobuf::Any* release_exdat();
  ::google::protobuf::Any* mutable_exdat();
  void set_allocated_exdat(::google::protobuf::Any* exdat);

  // int64 win = 1;
  void clear_win();
  static const int kWinFieldNumber = 1;
  ::google::protobuf::int64 win() const;
  void set_win(::google::protobuf::int64 value);

  // int64 realWin = 2;
  void clear_realwin();
  static const int kRealWinFieldNumber = 2;
  ::google::protobuf::int64 realwin() const;
  void set_realwin(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:natashapb.GameResultChunk)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::natashapb::GameResultInfo > lstgri_;
  ::google::protobuf::Any* exdat_;
  ::google::protobuf::int64 win_;
  ::google::protobuf::int64 realwin_;
  mutable int _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
  friend void ::protobuf_base_2eproto::InitDefaultsGameResultChunkImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SymbolLine

// repeated int32 xDat = 1;
inline int SymbolLine::xdat_size() const {
  return xdat_.size();
}
inline void SymbolLine::clear_xdat() {
  xdat_.Clear();
}
inline ::google::protobuf::int32 SymbolLine::xdat(int index) const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolLine.xDat)
  return xdat_.Get(index);
}
inline void SymbolLine::set_xdat(int index, ::google::protobuf::int32 value) {
  xdat_.Set(index, value);
  // @@protoc_insertion_point(field_set:natashapb.SymbolLine.xDat)
}
inline void SymbolLine::add_xdat(::google::protobuf::int32 value) {
  xdat_.Add(value);
  // @@protoc_insertion_point(field_add:natashapb.SymbolLine.xDat)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SymbolLine::xdat() const {
  // @@protoc_insertion_point(field_list:natashapb.SymbolLine.xDat)
  return xdat_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SymbolLine::mutable_xdat() {
  // @@protoc_insertion_point(field_mutable_list:natashapb.SymbolLine.xDat)
  return &xdat_;
}

// -------------------------------------------------------------------

// SymbolBlock

// repeated .natashapb.SymbolLine yDat = 1;
inline int SymbolBlock::ydat_size() const {
  return ydat_.size();
}
inline void SymbolBlock::clear_ydat() {
  ydat_.Clear();
}
inline ::natashapb::SymbolLine* SymbolBlock::mutable_ydat(int index) {
  // @@protoc_insertion_point(field_mutable:natashapb.SymbolBlock.yDat)
  return ydat_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::natashapb::SymbolLine >*
SymbolBlock::mutable_ydat() {
  // @@protoc_insertion_point(field_mutable_list:natashapb.SymbolBlock.yDat)
  return &ydat_;
}
inline const ::natashapb::SymbolLine& SymbolBlock::ydat(int index) const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock.yDat)
  return ydat_.Get(index);
}
inline ::natashapb::SymbolLine* SymbolBlock::add_ydat() {
  // @@protoc_insertion_point(field_add:natashapb.SymbolBlock.yDat)
  return ydat_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::natashapb::SymbolLine >&
SymbolBlock::ydat() const {
  // @@protoc_insertion_point(field_list:natashapb.SymbolBlock.yDat)
  return ydat_;
}

// -------------------------------------------------------------------

// SymbolBlock3X5

// int32 dat0_0 = 1;
inline void SymbolBlock3X5::clear_dat0_0() {
  dat0_0_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat0_0() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat0_0)
  return dat0_0_;
}
inline void SymbolBlock3X5::set_dat0_0(::google::protobuf::int32 value) {
  
  dat0_0_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat0_0)
}

// int32 dat0_1 = 2;
inline void SymbolBlock3X5::clear_dat0_1() {
  dat0_1_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat0_1() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat0_1)
  return dat0_1_;
}
inline void SymbolBlock3X5::set_dat0_1(::google::protobuf::int32 value) {
  
  dat0_1_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat0_1)
}

// int32 dat0_2 = 3;
inline void SymbolBlock3X5::clear_dat0_2() {
  dat0_2_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat0_2() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat0_2)
  return dat0_2_;
}
inline void SymbolBlock3X5::set_dat0_2(::google::protobuf::int32 value) {
  
  dat0_2_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat0_2)
}

// int32 dat0_3 = 4;
inline void SymbolBlock3X5::clear_dat0_3() {
  dat0_3_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat0_3() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat0_3)
  return dat0_3_;
}
inline void SymbolBlock3X5::set_dat0_3(::google::protobuf::int32 value) {
  
  dat0_3_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat0_3)
}

// int32 dat0_4 = 5;
inline void SymbolBlock3X5::clear_dat0_4() {
  dat0_4_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat0_4() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat0_4)
  return dat0_4_;
}
inline void SymbolBlock3X5::set_dat0_4(::google::protobuf::int32 value) {
  
  dat0_4_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat0_4)
}

// int32 dat1_0 = 6;
inline void SymbolBlock3X5::clear_dat1_0() {
  dat1_0_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat1_0() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat1_0)
  return dat1_0_;
}
inline void SymbolBlock3X5::set_dat1_0(::google::protobuf::int32 value) {
  
  dat1_0_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat1_0)
}

// int32 dat1_1 = 7;
inline void SymbolBlock3X5::clear_dat1_1() {
  dat1_1_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat1_1() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat1_1)
  return dat1_1_;
}
inline void SymbolBlock3X5::set_dat1_1(::google::protobuf::int32 value) {
  
  dat1_1_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat1_1)
}

// int32 dat1_2 = 8;
inline void SymbolBlock3X5::clear_dat1_2() {
  dat1_2_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat1_2() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat1_2)
  return dat1_2_;
}
inline void SymbolBlock3X5::set_dat1_2(::google::protobuf::int32 value) {
  
  dat1_2_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat1_2)
}

// int32 dat1_3 = 9;
inline void SymbolBlock3X5::clear_dat1_3() {
  dat1_3_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat1_3() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat1_3)
  return dat1_3_;
}
inline void SymbolBlock3X5::set_dat1_3(::google::protobuf::int32 value) {
  
  dat1_3_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat1_3)
}

// int32 dat1_4 = 10;
inline void SymbolBlock3X5::clear_dat1_4() {
  dat1_4_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat1_4() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat1_4)
  return dat1_4_;
}
inline void SymbolBlock3X5::set_dat1_4(::google::protobuf::int32 value) {
  
  dat1_4_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat1_4)
}

// int32 dat2_0 = 11;
inline void SymbolBlock3X5::clear_dat2_0() {
  dat2_0_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat2_0() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat2_0)
  return dat2_0_;
}
inline void SymbolBlock3X5::set_dat2_0(::google::protobuf::int32 value) {
  
  dat2_0_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat2_0)
}

// int32 dat2_1 = 12;
inline void SymbolBlock3X5::clear_dat2_1() {
  dat2_1_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat2_1() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat2_1)
  return dat2_1_;
}
inline void SymbolBlock3X5::set_dat2_1(::google::protobuf::int32 value) {
  
  dat2_1_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat2_1)
}

// int32 dat2_2 = 13;
inline void SymbolBlock3X5::clear_dat2_2() {
  dat2_2_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat2_2() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat2_2)
  return dat2_2_;
}
inline void SymbolBlock3X5::set_dat2_2(::google::protobuf::int32 value) {
  
  dat2_2_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat2_2)
}

// int32 dat2_3 = 14;
inline void SymbolBlock3X5::clear_dat2_3() {
  dat2_3_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat2_3() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat2_3)
  return dat2_3_;
}
inline void SymbolBlock3X5::set_dat2_3(::google::protobuf::int32 value) {
  
  dat2_3_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat2_3)
}

// int32 dat2_4 = 15;
inline void SymbolBlock3X5::clear_dat2_4() {
  dat2_4_ = 0;
}
inline ::google::protobuf::int32 SymbolBlock3X5::dat2_4() const {
  // @@protoc_insertion_point(field_get:natashapb.SymbolBlock3X5.dat2_4)
  return dat2_4_;
}
inline void SymbolBlock3X5::set_dat2_4(::google::protobuf::int32 value) {
  
  dat2_4_ = value;
  // @@protoc_insertion_point(field_set:natashapb.SymbolBlock3X5.dat2_4)
}

// -------------------------------------------------------------------

// RandomResult

// .google.protobuf.Any info = 1;
inline bool RandomResult::has_info() const {
  return this != internal_default_instance() && info_ != NULL;
}
inline const ::google::protobuf::Any& RandomResult::info() const {
  const ::google::protobuf::Any* p = info_;
  // @@protoc_insertion_point(field_get:natashapb.RandomResult.info)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Any*>(
      &::google::protobuf::_Any_default_instance_);
}
inline ::google::protobuf::Any* RandomResult::release_info() {
  // @@protoc_insertion_point(field_release:natashapb.RandomResult.info)
  
  ::google::protobuf::Any* temp = info_;
  info_ = NULL;
  return temp;
}
inline ::google::protobuf::Any* RandomResult::mutable_info() {
  
  if (info_ == NULL) {
    info_ = ::google::protobuf::Arena::Create< ::google::protobuf::Any >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:natashapb.RandomResult.info)
  return info_;
}
inline void RandomResult::set_allocated_info(::google::protobuf::Any* info) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(info_);
  }
  if (info) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      info = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, info, submessage_arena);
    }
    
  } else {
    
  }
  info_ = info;
  // @@protoc_insertion_point(field_set_allocated:natashapb.RandomResult.info)
}

// -------------------------------------------------------------------

// StaticCascadingRandomResult

// int32 reelsIndex = 1;
inline void StaticCascadingRandomResult::clear_reelsindex() {
  reelsindex_ = 0;
}
inline ::google::protobuf::int32 StaticCascadingRandomResult::reelsindex() const {
  // @@protoc_insertion_point(field_get:natashapb.StaticCascadingRandomResult.reelsIndex)
  return reelsindex_;
}
inline void StaticCascadingRandomResult::set_reelsindex(::google::protobuf::int32 value) {
  
  reelsindex_ = value;
  // @@protoc_insertion_point(field_set:natashapb.StaticCascadingRandomResult.reelsIndex)
}

// int32 downNums = 2;
inline void StaticCascadingRandomResult::clear_downnums() {
  downnums_ = 0;
}
inline ::google::protobuf::int32 StaticCascadingRandomResult::downnums() const {
  // @@protoc_insertion_point(field_get:natashapb.StaticCascadingRandomResult.downNums)
  return downnums_;
}
inline void StaticCascadingRandomResult::set_downnums(::google::protobuf::int32 value) {
  
  downnums_ = value;
  // @@protoc_insertion_point(field_set:natashapb.StaticCascadingRandomResult.downNums)
}

// -------------------------------------------------------------------

// Position2D

// int32 x = 1;
inline void Position2D::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 Position2D::x() const {
  // @@protoc_insertion_point(field_get:natashapb.Position2D.x)
  return x_;
}
inline void Position2D::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:natashapb.Position2D.x)
}

// int32 y = 2;
inline void Position2D::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 Position2D::y() const {
  // @@protoc_insertion_point(field_get:natashapb.Position2D.y)
  return y_;
}
inline void Position2D::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:natashapb.Position2D.y)
}

// -------------------------------------------------------------------

// GameResultInfo

// .natashapb.GAMERESULTTYPE typeGameResult = 1;
inline void GameResultInfo::clear_typegameresult() {
  typegameresult_ = 0;
}
inline ::natashapb::GAMERESULTTYPE GameResultInfo::typegameresult() const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultInfo.typeGameResult)
  return static_cast< ::natashapb::GAMERESULTTYPE >(typegameresult_);
}
inline void GameResultInfo::set_typegameresult(::natashapb::GAMERESULTTYPE value) {
  
  typegameresult_ = value;
  // @@protoc_insertion_point(field_set:natashapb.GameResultInfo.typeGameResult)
}

// repeated .natashapb.Position2D lstPos = 2;
inline int GameResultInfo::lstpos_size() const {
  return lstpos_.size();
}
inline void GameResultInfo::clear_lstpos() {
  lstpos_.Clear();
}
inline ::natashapb::Position2D* GameResultInfo::mutable_lstpos(int index) {
  // @@protoc_insertion_point(field_mutable:natashapb.GameResultInfo.lstPos)
  return lstpos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::natashapb::Position2D >*
GameResultInfo::mutable_lstpos() {
  // @@protoc_insertion_point(field_mutable_list:natashapb.GameResultInfo.lstPos)
  return &lstpos_;
}
inline const ::natashapb::Position2D& GameResultInfo::lstpos(int index) const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultInfo.lstPos)
  return lstpos_.Get(index);
}
inline ::natashapb::Position2D* GameResultInfo::add_lstpos() {
  // @@protoc_insertion_point(field_add:natashapb.GameResultInfo.lstPos)
  return lstpos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::natashapb::Position2D >&
GameResultInfo::lstpos() const {
  // @@protoc_insertion_point(field_list:natashapb.GameResultInfo.lstPos)
  return lstpos_;
}

// int32 symbol = 3;
inline void GameResultInfo::clear_symbol() {
  symbol_ = 0;
}
inline ::google::protobuf::int32 GameResultInfo::symbol() const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultInfo.symbol)
  return symbol_;
}
inline void GameResultInfo::set_symbol(::google::protobuf::int32 value) {
  
  symbol_ = value;
  // @@protoc_insertion_point(field_set:natashapb.GameResultInfo.symbol)
}

// repeated int32 lstSymbol = 4;
inline int GameResultInfo::lstsymbol_size() const {
  return lstsymbol_.size();
}
inline void GameResultInfo::clear_lstsymbol() {
  lstsymbol_.Clear();
}
inline ::google::protobuf::int32 GameResultInfo::lstsymbol(int index) const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultInfo.lstSymbol)
  return lstsymbol_.Get(index);
}
inline void GameResultInfo::set_lstsymbol(int index, ::google::protobuf::int32 value) {
  lstsymbol_.Set(index, value);
  // @@protoc_insertion_point(field_set:natashapb.GameResultInfo.lstSymbol)
}
inline void GameResultInfo::add_lstsymbol(::google::protobuf::int32 value) {
  lstsymbol_.Add(value);
  // @@protoc_insertion_point(field_add:natashapb.GameResultInfo.lstSymbol)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GameResultInfo::lstsymbol() const {
  // @@protoc_insertion_point(field_list:natashapb.GameResultInfo.lstSymbol)
  return lstsymbol_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GameResultInfo::mutable_lstsymbol() {
  // @@protoc_insertion_point(field_mutable_list:natashapb.GameResultInfo.lstSymbol)
  return &lstsymbol_;
}

// int64 win = 5;
inline void GameResultInfo::clear_win() {
  win_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GameResultInfo::win() const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultInfo.win)
  return win_;
}
inline void GameResultInfo::set_win(::google::protobuf::int64 value) {
  
  win_ = value;
  // @@protoc_insertion_point(field_set:natashapb.GameResultInfo.win)
}

// int64 realWin = 6;
inline void GameResultInfo::clear_realwin() {
  realwin_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GameResultInfo::realwin() const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultInfo.realWin)
  return realwin_;
}
inline void GameResultInfo::set_realwin(::google::protobuf::int64 value) {
  
  realwin_ = value;
  // @@protoc_insertion_point(field_set:natashapb.GameResultInfo.realWin)
}

// .google.protobuf.Any exDat = 7;
inline bool GameResultInfo::has_exdat() const {
  return this != internal_default_instance() && exdat_ != NULL;
}
inline const ::google::protobuf::Any& GameResultInfo::exdat() const {
  const ::google::protobuf::Any* p = exdat_;
  // @@protoc_insertion_point(field_get:natashapb.GameResultInfo.exDat)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Any*>(
      &::google::protobuf::_Any_default_instance_);
}
inline ::google::protobuf::Any* GameResultInfo::release_exdat() {
  // @@protoc_insertion_point(field_release:natashapb.GameResultInfo.exDat)
  
  ::google::protobuf::Any* temp = exdat_;
  exdat_ = NULL;
  return temp;
}
inline ::google::protobuf::Any* GameResultInfo::mutable_exdat() {
  
  if (exdat_ == NULL) {
    exdat_ = ::google::protobuf::Arena::Create< ::google::protobuf::Any >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:natashapb.GameResultInfo.exDat)
  return exdat_;
}
inline void GameResultInfo::set_allocated_exdat(::google::protobuf::Any* exdat) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(exdat_);
  }
  if (exdat) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      exdat = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, exdat, submessage_arena);
    }
    
  } else {
    
  }
  exdat_ = exdat;
  // @@protoc_insertion_point(field_set_allocated:natashapb.GameResultInfo.exDat)
}

// -------------------------------------------------------------------

// GameResultChunk

// int64 win = 1;
inline void GameResultChunk::clear_win() {
  win_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GameResultChunk::win() const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultChunk.win)
  return win_;
}
inline void GameResultChunk::set_win(::google::protobuf::int64 value) {
  
  win_ = value;
  // @@protoc_insertion_point(field_set:natashapb.GameResultChunk.win)
}

// int64 realWin = 2;
inline void GameResultChunk::clear_realwin() {
  realwin_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GameResultChunk::realwin() const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultChunk.realWin)
  return realwin_;
}
inline void GameResultChunk::set_realwin(::google::protobuf::int64 value) {
  
  realwin_ = value;
  // @@protoc_insertion_point(field_set:natashapb.GameResultChunk.realWin)
}

// repeated .natashapb.GameResultInfo lstGRI = 3;
inline int GameResultChunk::lstgri_size() const {
  return lstgri_.size();
}
inline void GameResultChunk::clear_lstgri() {
  lstgri_.Clear();
}
inline ::natashapb::GameResultInfo* GameResultChunk::mutable_lstgri(int index) {
  // @@protoc_insertion_point(field_mutable:natashapb.GameResultChunk.lstGRI)
  return lstgri_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::natashapb::GameResultInfo >*
GameResultChunk::mutable_lstgri() {
  // @@protoc_insertion_point(field_mutable_list:natashapb.GameResultChunk.lstGRI)
  return &lstgri_;
}
inline const ::natashapb::GameResultInfo& GameResultChunk::lstgri(int index) const {
  // @@protoc_insertion_point(field_get:natashapb.GameResultChunk.lstGRI)
  return lstgri_.Get(index);
}
inline ::natashapb::GameResultInfo* GameResultChunk::add_lstgri() {
  // @@protoc_insertion_point(field_add:natashapb.GameResultChunk.lstGRI)
  return lstgri_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::natashapb::GameResultInfo >&
GameResultChunk::lstgri() const {
  // @@protoc_insertion_point(field_list:natashapb.GameResultChunk.lstGRI)
  return lstgri_;
}

// .google.protobuf.Any exDat = 4;
inline bool GameResultChunk::has_exdat() const {
  return this != internal_default_instance() && exdat_ != NULL;
}
inline const ::google::protobuf::Any& GameResultChunk::exdat() const {
  const ::google::protobuf::Any* p = exdat_;
  // @@protoc_insertion_point(field_get:natashapb.GameResultChunk.exDat)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Any*>(
      &::google::protobuf::_Any_default_instance_);
}
inline ::google::protobuf::Any* GameResultChunk::release_exdat() {
  // @@protoc_insertion_point(field_release:natashapb.GameResultChunk.exDat)
  
  ::google::protobuf::Any* temp = exdat_;
  exdat_ = NULL;
  return temp;
}
inline ::google::protobuf::Any* GameResultChunk::mutable_exdat() {
  
  if (exdat_ == NULL) {
    exdat_ = ::google::protobuf::Arena::Create< ::google::protobuf::Any >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:natashapb.GameResultChunk.exDat)
  return exdat_;
}
inline void GameResultChunk::set_allocated_exdat(::google::protobuf::Any* exdat) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(exdat_);
  }
  if (exdat) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      exdat = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, exdat, submessage_arena);
    }
    
  } else {
    
  }
  exdat_ = exdat;
  // @@protoc_insertion_point(field_set_allocated:natashapb.GameResultChunk.exDat)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace natashapb

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::natashapb::GAMERESULTTYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::natashapb::GAMERESULTTYPE>() {
  return ::natashapb::GAMERESULTTYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_base_2eproto__INCLUDED
