// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tlod.proto

#ifndef PROTOBUF_tlod_2eproto__INCLUDED
#define PROTOBUF_tlod_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_tlod_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsBGUserInfoImpl();
void InitDefaultsBGUserInfo();
void InitDefaultsFGUserInfoImpl();
void InitDefaultsFGUserInfo();
inline void InitDefaults() {
  InitDefaultsBGUserInfo();
  InitDefaultsFGUserInfo();
}
}  // namespace protobuf_tlod_2eproto
namespace tlodpb {
class BGUserInfo;
class BGUserInfoDefaultTypeInternal;
extern BGUserInfoDefaultTypeInternal _BGUserInfo_default_instance_;
class FGUserInfo;
class FGUserInfoDefaultTypeInternal;
extern FGUserInfoDefaultTypeInternal _FGUserInfo_default_instance_;
}  // namespace tlodpb
namespace google {
namespace protobuf {
template<> ::tlodpb::BGUserInfo* Arena::Create< ::tlodpb::BGUserInfo>(Arena*);
template<> ::tlodpb::FGUserInfo* Arena::Create< ::tlodpb::FGUserInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tlodpb {

// ===================================================================

class BGUserInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tlodpb.BGUserInfo) */ {
 public:
  BGUserInfo();
  virtual ~BGUserInfo();

  BGUserInfo(const BGUserInfo& from);

  inline BGUserInfo& operator=(const BGUserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BGUserInfo(BGUserInfo&& from) noexcept
    : BGUserInfo() {
    *this = ::std::move(from);
  }

  inline BGUserInfo& operator=(BGUserInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BGUserInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BGUserInfo* internal_default_instance() {
    return reinterpret_cast<const BGUserInfo*>(
               &_BGUserInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BGUserInfo* other);
  friend void swap(BGUserInfo& a, BGUserInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BGUserInfo* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<BGUserInfo>(NULL);
  }

  BGUserInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<BGUserInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BGUserInfo& from);
  void MergeFrom(const BGUserInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BGUserInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:tlodpb.BGUserInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_tlod_2eproto::TableStruct;
  friend void ::protobuf_tlod_2eproto::InitDefaultsBGUserInfoImpl();
};
// -------------------------------------------------------------------

class FGUserInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tlodpb.FGUserInfo) */ {
 public:
  FGUserInfo();
  virtual ~FGUserInfo();

  FGUserInfo(const FGUserInfo& from);

  inline FGUserInfo& operator=(const FGUserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FGUserInfo(FGUserInfo&& from) noexcept
    : FGUserInfo() {
    *this = ::std::move(from);
  }

  inline FGUserInfo& operator=(FGUserInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FGUserInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FGUserInfo* internal_default_instance() {
    return reinterpret_cast<const FGUserInfo*>(
               &_FGUserInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(FGUserInfo* other);
  friend void swap(FGUserInfo& a, FGUserInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FGUserInfo* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<FGUserInfo>(NULL);
  }

  FGUserInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<FGUserInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FGUserInfo& from);
  void MergeFrom(const FGUserInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FGUserInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:tlodpb.FGUserInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_tlod_2eproto::TableStruct;
  friend void ::protobuf_tlod_2eproto::InitDefaultsFGUserInfoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BGUserInfo

// -------------------------------------------------------------------

// FGUserInfo

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tlodpb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tlod_2eproto__INCLUDED
