// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tlod.proto

#include "tlod.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace tlodpb {
class BGUserInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BGUserInfo>
      _instance;
} _BGUserInfo_default_instance_;
class FGUserInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FGUserInfo>
      _instance;
} _FGUserInfo_default_instance_;
}  // namespace tlodpb
namespace protobuf_tlod_2eproto {
void InitDefaultsBGUserInfoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tlodpb::_BGUserInfo_default_instance_;
    new (ptr) ::tlodpb::BGUserInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tlodpb::BGUserInfo::InitAsDefaultInstance();
}

void InitDefaultsBGUserInfo() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsBGUserInfoImpl);
}

void InitDefaultsFGUserInfoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tlodpb::_FGUserInfo_default_instance_;
    new (ptr) ::tlodpb::FGUserInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tlodpb::FGUserInfo::InitAsDefaultInstance();
}

void InitDefaultsFGUserInfo() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFGUserInfoImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tlodpb::BGUserInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tlodpb::FGUserInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tlodpb::BGUserInfo)},
  { 5, -1, sizeof(::tlodpb::FGUserInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tlodpb::_BGUserInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tlodpb::_FGUserInfo_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tlod.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ntlod.proto\022\006tlodpb\"\014\n\nBGUserInfo\"\014\n\nFG"
      "UserInfob\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 56);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tlod.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_tlod_2eproto
namespace tlodpb {

// ===================================================================

void BGUserInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BGUserInfo::BGUserInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tlod_2eproto::InitDefaultsBGUserInfo();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tlodpb.BGUserInfo)
}
BGUserInfo::BGUserInfo(const BGUserInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tlodpb.BGUserInfo)
}

void BGUserInfo::SharedCtor() {
  _cached_size_ = 0;
}

BGUserInfo::~BGUserInfo() {
  // @@protoc_insertion_point(destructor:tlodpb.BGUserInfo)
  SharedDtor();
}

void BGUserInfo::SharedDtor() {
}

void BGUserInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BGUserInfo::descriptor() {
  ::protobuf_tlod_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tlod_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BGUserInfo& BGUserInfo::default_instance() {
  ::protobuf_tlod_2eproto::InitDefaultsBGUserInfo();
  return *internal_default_instance();
}


void BGUserInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:tlodpb.BGUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool BGUserInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tlodpb.BGUserInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:tlodpb.BGUserInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tlodpb.BGUserInfo)
  return false;
#undef DO_
}

void BGUserInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tlodpb.BGUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tlodpb.BGUserInfo)
}

::google::protobuf::uint8* BGUserInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tlodpb.BGUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tlodpb.BGUserInfo)
  return target;
}

size_t BGUserInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tlodpb.BGUserInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BGUserInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tlodpb.BGUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const BGUserInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BGUserInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tlodpb.BGUserInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tlodpb.BGUserInfo)
    MergeFrom(*source);
  }
}

void BGUserInfo::MergeFrom(const BGUserInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tlodpb.BGUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void BGUserInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tlodpb.BGUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BGUserInfo::CopyFrom(const BGUserInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tlodpb.BGUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BGUserInfo::IsInitialized() const {
  return true;
}

void BGUserInfo::Swap(BGUserInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BGUserInfo::InternalSwap(BGUserInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BGUserInfo::GetMetadata() const {
  protobuf_tlod_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tlod_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void FGUserInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FGUserInfo::FGUserInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tlod_2eproto::InitDefaultsFGUserInfo();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tlodpb.FGUserInfo)
}
FGUserInfo::FGUserInfo(const FGUserInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tlodpb.FGUserInfo)
}

void FGUserInfo::SharedCtor() {
  _cached_size_ = 0;
}

FGUserInfo::~FGUserInfo() {
  // @@protoc_insertion_point(destructor:tlodpb.FGUserInfo)
  SharedDtor();
}

void FGUserInfo::SharedDtor() {
}

void FGUserInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FGUserInfo::descriptor() {
  ::protobuf_tlod_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tlod_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FGUserInfo& FGUserInfo::default_instance() {
  ::protobuf_tlod_2eproto::InitDefaultsFGUserInfo();
  return *internal_default_instance();
}


void FGUserInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:tlodpb.FGUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool FGUserInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tlodpb.FGUserInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:tlodpb.FGUserInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tlodpb.FGUserInfo)
  return false;
#undef DO_
}

void FGUserInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tlodpb.FGUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tlodpb.FGUserInfo)
}

::google::protobuf::uint8* FGUserInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tlodpb.FGUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tlodpb.FGUserInfo)
  return target;
}

size_t FGUserInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tlodpb.FGUserInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FGUserInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tlodpb.FGUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const FGUserInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FGUserInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tlodpb.FGUserInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tlodpb.FGUserInfo)
    MergeFrom(*source);
  }
}

void FGUserInfo::MergeFrom(const FGUserInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tlodpb.FGUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void FGUserInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tlodpb.FGUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FGUserInfo::CopyFrom(const FGUserInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tlodpb.FGUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FGUserInfo::IsInitialized() const {
  return true;
}

void FGUserInfo::Swap(FGUserInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FGUserInfo::InternalSwap(FGUserInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FGUserInfo::GetMetadata() const {
  protobuf_tlod_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tlod_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tlodpb
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tlodpb::BGUserInfo* Arena::Create< ::tlodpb::BGUserInfo >(Arena* arena) {
  return Arena::CreateInternal< ::tlodpb::BGUserInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tlodpb::FGUserInfo* Arena::Create< ::tlodpb::FGUserInfo >(Arena* arena) {
  return Arena::CreateInternal< ::tlodpb::FGUserInfo >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
